### ISSUE TITLE
SyntaxError: Unexpected token R     at Object.parse (native)

### ISSUE THREAD

**Issue by fa1115** [couchbaselabs/user-profile-generator#1]
Hi,
I am trying to run this tool on a Couchbase 3.0.2 cluster.  I am getting the following error:

SyntaxError: Unexpected token R
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/root/node_modules/user-profile-generator/model/test.js:51:33)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

It happens in the function below when it's trying to parse the JSON object.
function checkOps(opsV) {
    http.get("http://" + endPoint + "/pools/default/buckets/user", function (res) {
        var data="";
        res.setEncoding('utf8');
        res.on('data', function (chunk) {
            data += chunk;
        });
        res.on('end',function(){
                var parsed=JSON.parse(data);
                opsV(parsed.basicStats.opsPerSec);
            });
        });
}

Any help would be greatly appreciated.

**Comment by fa1115** [comment]
Sorry had the bucket name wrong :)
